# Site settings
title: "fireflies.ai"
description: "The fireflies.ai Blog Site."
baseurl: "willian-justen-blog/" # the subpath of your site, e.g. /blog
url: "http://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: fireflies.ai
user_description: The most helpful slack bot.
user_title: Slack Bot
email: support@fireflies.ai
twitter_username: firefliesai
github_username:
gplus_username: 
disqus_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Join Us!
    url: /https://fireflies.ai/teams
  - title: Become More Productive!
    url: https://fireflies.ai

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
